version: '3'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
      - "8081:80"
      - "24:22"     #Default set it to "22:22", changed to test with github actions
      - "443:443"
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    tty: true

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    privileged: true
    ports:
      - "8095:8080"
      - "5000:5000"
      - "25:22"     ##Default set it to "22:22", changed to test with github actions
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'     #/usr/local/bin/docker for MacOS and /usr/bin/docker for Ubuntu <- which docker
      #- '/usr/local/bin/docker:/usr/local/bin/docker'
    tty: true

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner
    privileged: true
    volumes: 
      - 'gitlab_runner_config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    tty: true

  sonarqube:
    container_name: sonarqube
    image: bitnami/sonarqube
    ports: 
      - "9000:9000"
    volumes: 
      - 'sonarqube_data:/bitnami'
    depends_on: 
      - postgresql
    environment: 
      - SONARQUBE_DATABASE_USER=sonarqube
      - SONARQUBE_DATABASE_NAME=sonarqube
      - SONARQUBE_DATABASE_PASSWORD=sonarqube1234
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_USERNAME=admin
      - SONARQUBE_PASSWORD=admin
      - SONARQUBE_PORT_NUMBER=9000
    tty: true

  postgresql:
    container_name: postgresql
    image: bitnami/postgresql
    volumes: 
      - 'postgresql_data:/bitnami'
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USER=sonarqube
      - POSTGRESQL_DATABASE=sonarqube
      - POSTGRESQL_PASSWORD=sonarqube1234
    tty: true

volumes:
  jenkins_data:
  gitlab_data:
  gitlab_config:
  gitlab_logs:
  gitlab_runner_config:
  sonarqube_data:
  postgresql_data: