version: '3'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
      - "8081:80"
      - "24:22"     #Default set it to "22:22", changed to test with github actions
      - "443:443"
    tty: true

  jenkins:
    container_name: jenkins
    image:  jenkins/jenkins
    ports:
      - "8095:8080"
      - "5000:5000"
      - "25:22"     ##Default set it to "22:22", changed to test with github actions
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    tty: true

volumes:
  jenkins_home:
