version: '3'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
      - "8081:80"
      - "24:22"     #Default set it to "22:22", changed to test with github actions
      - "443:443"
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    tty: true

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    privileged: true
    ports:
      - "8095:8080"
      - "5000:5000"
      - "25:22"     ##Default set it to "22:22", changed to test with github actions
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'     #/usr/local/bin/docker for MacOS and /usr/bin/docker for Ubuntu <- which docker
    tty: true

volumes:
  jenkins_data:
  gitlab_data:
  gitlab_config:
  gitlab_logs:
