version: '3'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
      - "8081:80"
      - "24:22"     #Default set it to "22:22", changed to test with github actions
      - "443:443"
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    tty: true

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    privileged: true
    ports:
      - "8082:8080"
      - "5000:5000"
      - "25:22"     ##Default set it to "22:22", changed to test with github actions
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/usr/bin/docker'     #/usr/local/bin/docker for MacOS and /usr/bin/docker for Ubuntu <- which docker
    tty: true

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner
    privileged: true
    volumes: 
      - 'gitlab_runner_config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local//bin/docker:/usr/bin/docker'
    tty: true

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports: 
      - "8083:9000"
    volumes: 
      - 'sonarqube_data:/opt/sonarqube'
    depends_on: 
      - postgresql
    environment: 
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql:5432/sonarqube
    tty: true

  postgresql:
    container_name: postgresql
    image: postgres
    volumes: 
      - 'postgresql_data:/var/lib/postgresql'
    environment: 
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
    tty: true

volumes:
  jenkins_data:
  gitlab_data:
  gitlab_config:
  gitlab_logs:
  gitlab_runner_config:
  sonarqube_data:
  postgresql_data: